### ISSUE TITLE
eNMS doesn't start, fresh install of Ubuntu 19.04

### ISSUE THREAD

**Issue by dd1245** [eNMS-automation/eNMS#209]
Hi. I'm trying to test eNMS on a fresh Ubuntu 19.04 server VM. I've install the required using pip3 and all seemed ok. However when I try to start in development mode...

```
root@enmsu19:/opt/eNMS# flask run --host=0.0.0.0
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/opt/eNMS/app.py", line 1, in <module>
    from eNMS.framework import create_app
  File "/opt/eNMS/eNMS/__init__.py", line 1, in <module>
    from eNMS.controller import App
  File "/opt/eNMS/eNMS/controller/__init__.py", line 1, in <module>
    from eNMS.controller.administration import AdministrationController
  File "/opt/eNMS/eNMS/controller/administration.py", line 6, in <module>
    from ldap3 import Connection, NTLM, SUBTREE
  File "/usr/local/lib/python3.7/dist-packages/ldap3/__init__.py", line 139, in <module>
    from .core.connection import Connection
  File "/usr/local/lib/python3.7/dist-packages/ldap3/core/connection.py", line 44, in <module>
    from ..operation.compare import compare_operation, compare_request_to_dict
  File "/usr/local/lib/python3.7/dist-packages/ldap3/operation/compare.py", line 28, in <module>
    from ..operation.search import ava_to_dict
  File "/usr/local/lib/python3.7/dist-packages/ldap3/operation/search.py", line 41, in <module>
    from pyasn1.error import PyAsn1UnicodeDecodeError
ImportError: cannot import name 'PyAsn1UnicodeDecodeError' from 'pyasn1.error' (/usr/lib/python3/dist-packages/pyasn1/error.py)
```

I reviewed the pip3 install and noticed the below. Is this why it doesn't start? All packages where installed through the requirements.txt and server had nothing installed before this.

```
flask 1.1.1 has requirement Jinja2>=2.10.1, but you'll have jinja2 2.10 which is incompatible.
junos-eznc 2.2.1 has requirement PyYAML>=5.1, but you'll have pyyaml 3.13 which is incompatible.
napalm 2.5.0 has requirement netmiko==2.4.2, but you'll have netmiko 3.0.0 which is incompatible.
```

Any ideas on how I can resolve this? the Python version is 3.7.3

**Comment by jpobeda** [comment]
You are better off creating virtual environment and install it from there.

**Comment by afourmy** [comment]
this is an environment problem, unrelated to enms
you can try/except ldap imports and it'll start
