### ISSUE TITLE
AttributeError: 'UnboundField' object has no attribute 'entries'

### ISSUE THREAD

**Issue by dd1245** [eNMS-automation/eNMS#299]
Hi.

When trying to edit any services I get a red box appears with "Error 500" whenever I click save. This is the message in the log. any ideas? 

2021-01-11 18:17:16,536 ERROR    Exception on /update/netmiko_backup_service [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/eNMS/eNMS/server.py", line 77, in decorated_function
    return function(*args, **kwargs)
  File "/opt/eNMS/eNMS/server.py", line 329, in route
    kwargs = form.form_postprocessing(request.form)
  File "/opt/eNMS/eNMS/forms/__init__.py", line 130, in form_postprocessing
    for entry in getattr(cls, property).entries:
AttributeError: 'UnboundField' object has no attribute 'entries'

**Comment by afourmy** [comment]
just pushed a fix, it should be working now... the bug only affected the netmiko backup services
can you test and let me know ?

**Comment by dd1245** [comment]
All working now. Thanks for the quick fix!
