### ISSUE TITLE
BUG Syslog-triggered automation not working

### ISSUE THREAD

**Issue by LensHunnel** [eNMS-automation/eNMS#317]
Hi,

First of all, i would like to say that you made a good job! 

I recently got an issue testing eNMS(v3.22.3) features, the Syslog-triggered automation is not working. it seems like Service object doesn't have a run attribute.

```bash
/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/var/www/html/eNMS/eNMS/controller/syslog.py", line 30, in handle
    event.match_log(**properties)
  File "/var/www/html/eNMS/eNMS/models/scheduling.py", line 143, in match_log
    self.service.run()
  File "/var/www/html/eNMS/eNMS/models/base.py", line 33, in __getattribute__
    return super().__getattribute__(property)
AttributeError: 'Workflow' object has no attribute 'run'
----------------------------------------
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/var/www/html/eNMS/eNMS/controller/syslog.py", line 30, in handle
    event.match_log(**properties)
  File "/var/www/html/eNMS/eNMS/models/scheduling.py", line 143, in match_log
    self.service.run()```

**Comment by afourmy** [comment]
Thanks for the report. It's a bug indeed, but since this feature isn't used by any of our customers (most companies already have a dedicated solution to process & store logs (e.g Splunk), so they can use it to make REST calls to eNMS and don't need eNMS to act as a syslog server), we've decided to remove it in the next release.
For that reason it doesn't make sense to fix it in v3.22.3
