### ISSUE TITLE
eNMS Random Internal Server Errors

### ISSUE THREAD

**Issue by jsmith7735** [eNMS-automation/eNMS#321]
I am noticing random Internal Server Errors being returned from the eNMS application. I have not been able to nail down the cause of the issue as of yet. At first glance, it appears the issue may be related to loss of connectivity to the database or maybe that is just a symptom. 

1. Are there additional log files that I should review?
2. I have reviewed the nginx logs at `/var/log/nginx` these do not reflect any outstanding issue
3. The log files below are not updated when this issue is going on.
  `/var/www/eNMS/logs/enms.log`
  `/var/www/eNMS/logs/error.log`
4. Resolving the issue requires a restart of the eNMS service:` service enms restart`

Output from `sudo systemctl status enms`:
```
Apr 05 21:12:34 cersrenms01 gunicorn[84133]:     conn = self._revalidate_connection()
Apr 05 21:12:34 cersrenms01 gunicorn[84133]:   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 469, in _revalidate_connection
Apr 05 21:12:34 cersrenms01 gunicorn[84133]:     raise exc.InvalidRequestError(
Apr 05 21:12:34 cersrenms01 gunicorn[84133]: sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
Apr 05 21:12:34 cersrenms01 gunicorn[84133]: [SQL: SELECT user.id AS user_id, user.name AS user_name, user.description AS user_description, user.`groups` AS user_groups, user.email AS user_email, user.password AS user_password, user.a>
Apr 05 21:12:34 cersrenms01 gunicorn[84133]: FROM user
Apr 05 21:12:34 cersrenms01 gunicorn[84133]: WHERE user.name = %s
Apr 05 21:12:34 cersrenms01 gunicorn[84133]:  LIMIT %s]
Apr 05 21:12:34 cersrenms01 gunicorn[84133]: [parameters: [immutabledict({})]]
Apr 05 21:12:34 cersrenms01 gunicorn[84133]: 127.0.0.1 - - [05/Apr/2021:21:12:34 +0000] "GET /task_table HTTP/1.0" 500 0 "-" "-"
```

**Comment by jsmith7735** [comment]
Additional logs that may help diagnose the issue.

The logs below are in reverse order.
```
Apr 10 23:21:40 cersrenms01 gunicorn[249399]: Traceback (most recent call last):
Apr 10 23:21:40 cersrenms01 gunicorn[249399]: The above exception was the direct cause of the following exception:
Apr 10 23:21:40 cersrenms01 gunicorn[249399]: MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')
Apr 10 23:21:40 cersrenms01 gunicorn[249399]:     _mysql.connection.query(self, query)
Apr 10 23:21:40 cersrenms01 gunicorn[249399]:   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 259, in query
Apr 10 23:21:40 cersrenms01 gunicorn[249399]:     db.query(q)
Apr 10 23:21:40 cersrenms01 gunicorn[249399]:   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 319, in _query
Apr 10 23:21:40 cersrenms01 gunicorn[249399]:     res = self._query(query)
Apr 10 23:21:40 cersrenms01 gunicorn[249399]:   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 206, in execute
Apr 10 23:21:40 cersrenms01 gunicorn[249399]:     cursor.execute(statement, parameters)
Apr 10 23:21:40 cersrenms01 gunicorn[249399]:   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Apr 10 23:21:40 cersrenms01 gunicorn[249399]:     self.dialect.do_execute(
Apr 10 23:21:40 cersrenms01 gunicorn[249399]:   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
Apr 10 23:21:40 cersrenms01 gunicorn[249399]: Traceback (most recent call last):
Apr 10 23:21:40 cersrenms01 gunicorn[249399]: Exception in thread Thread-1:
Apr 10 23:21:38 cersrenms01 gunicorn[249399]: 2021-04-10 23:21:38,977 DEBUG    EOF in transport thread
```

**Comment by afourmy** [comment]
this looks like an issue with how MySQL is configured in your environment, not eNMS.
try to tweak relevant parameters in MySQL conf. example of relevant parameters and ideal value

```
max_allowed_packet = 128M
wait_timeout = 31536000
innodb_buffer_pool_size = 512M
innodb_log_file_size = 64M
binlog_cache_size = 16M
thread_cache_size = 18
join_buffer_size=256K
```

**Comment by jsmith7735** [comment]
@afourmy,

Thanks for the help. Things appear to be working better now. We have been running stable for the last week.

The following were already higher numbers than he asked:
max_allowed_packet = 536870912
innodb_buffer_pool_size = 15032385536
join_buffer_size = 262144

This I increased to his numbers:
thread_cache_size = 18

This can’t go as high as requested, but I did increase to the max:
wait_timeout = 2147483 (Max)

These I cannot change, it’s managed by Azure:
innodb_log_file_size = (CANNOT EDIT)
binlog_cache_size = (CANNOT EDIT)
