### ISSUE TITLE
JSONDecodeError when starting Flask or Gunicorn

### ISSUE THREAD

**Issue by nkane2898** [eNMS-automation/eNMS#325]
I performed a git pull origin master to update. The only different I have in mysetup is that use_vault is true in the settings.json file. When I try to start flask or gunicorn it fails with a json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) message.

diff --git a/build/scripts/deploy.sh b/build/scripts/deploy.sh
old mode 100644
new mode 100755
diff --git a/build/scripts/plugin.sh b/build/scripts/plugin.sh
old mode 100644
new mode 100755
diff --git a/build/scripts/run.sh b/build/scripts/run.sh
old mode 100644
new mode 100755
diff --git a/setup/settings.json b/setup/settings.json
index a32715487..66d8b9519 100644
--- a/setup/settings.json
+++ b/setup/settings.json
@@ -117,6 +117,6 @@
   },
   "vault": {
     "unseal_vault": false,
-    "use_vault": false
+    "use_vault": true
   }
 }

Flask:
flask run --host=0.0.0.0
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/nkane/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/nkane/.local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/nkane/.local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/nkane/.local/lib/python3.8/site-packages/flask/cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/nkane/.local/lib/python3.8/site-packages/flask/cli.py", line 305, in __init__
    self._load_unlocked()
  File "/home/nkane/.local/lib/python3.8/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/nkane/.local/lib/python3.8/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/home/nkane/.local/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/nkane/eNMS/app.py", line 1, in <module>
    from eNMS.server import server as app  # noqa: F401
  File "/home/nkane/eNMS/eNMS/__init__.py", line 1, in <module>
    from eNMS.controller import App
  File "/home/nkane/eNMS/eNMS/controller/__init__.py", line 3, in <module>
    from eNMS.controller.administration import AdministrationController
  File "/home/nkane/eNMS/eNMS/controller/administration.py", line 19, in <module>
    from eNMS.controller.base import BaseController
  File "/home/nkane/eNMS/eNMS/controller/base.py", line 41, in <module>
    from eNMS.database import db
  File "/home/nkane/eNMS/eNMS/database.py", line 32, in <module>
    from eNMS.setup import database as database_settings, properties, rbac as rbac_settings
  File "/home/nkane/eNMS/eNMS/setup.py", line 6, in <module>
    locals()[setup_file.stem] = load(file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Gunicorn:
gunicorn --config gunicorn.py app:app
[2021-04-09 18:10:27 -0400] [16224] [DEBUG] Current configuration:
  config: gunicorn.py
  bind: ['0.0.0.0:5000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 3000
  graceful_timeout: 3000
  keepalive: 2
  limit_request_line: 0
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: True
  sendfile: None
  reuse_port: False
  chdir: /home/nkane/eNMS
  daemon: False
  raw_env: ['TERM=screen']
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: -
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: True
  statsd_host: None
  dogstatsd_tags:
  statsd_prefix:
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f59de688dc0>
  on_reload: <function OnReload.on_reload at 0x7f59de688ee0>
  when_ready: <function WhenReady.when_ready at 0x7f59de619040>
  pre_fork: <function Prefork.pre_fork at 0x7f59de619160>
  post_fork: <function post_fork at 0x7f59dea81a60>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f59de6193a0>
  worker_int: <function WorkerInt.worker_int at 0x7f59de6194c0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f59de6195e0>
  pre_exec: <function PreExec.pre_exec at 0x7f59de619700>
  pre_request: <function PreRequest.pre_request at 0x7f59de619820>
  post_request: <function PostRequest.post_request at 0x7f59de6198b0>
  child_exit: <function ChildExit.child_exit at 0x7f59de6199d0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f59de619af0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f59de619c10>
  on_exit: <function OnExit.on_exit at 0x7f59de619d30>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
Traceback (most recent call last):
  File "/home/nkane/.local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/nkane/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/nkane/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/home/nkane/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/nkane/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/home/nkane/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/home/nkane/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nkane/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/nkane/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/nkane/.local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nkane/eNMS/app.py", line 1, in <module>
    from eNMS.server import server as app  # noqa: F401
  File "/home/nkane/eNMS/eNMS/__init__.py", line 1, in <module>
    from eNMS.controller import App
  File "/home/nkane/eNMS/eNMS/controller/__init__.py", line 3, in <module>
    from eNMS.controller.administration import AdministrationController
  File "/home/nkane/eNMS/eNMS/controller/administration.py", line 19, in <module>
    from eNMS.controller.base import BaseController
  File "/home/nkane/eNMS/eNMS/controller/base.py", line 41, in <module>
    from eNMS.database import db
  File "/home/nkane/eNMS/eNMS/database.py", line 32, in <module>
    from eNMS.setup import database as database_settings, properties, rbac as rbac_settings
  File "/home/nkane/eNMS/eNMS/setup.py", line 6, in <module>
    locals()[setup_file.stem] = load(file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by afourmy** [comment]
looks like one of the file in the setup folder is not a valid JSON file.
