### ISSUE TITLE
Sqlalchemy Postgresql Error

### ISSUE THREAD

**Issue by nkane2898** [eNMS-automation/eNMS#327]
The Configuration Backup (NAPALM) is failing to backup a Cisco 2921. It is throwing a InvalidTextRepresentation error.

[Regression Workflow: Operational Data Backup (admin)] Configuration Backup (NAPALM) 

2021-04-12 14:57:33,001 ERROR    Traceback (most recent call last):
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: "%"
LINE 4: WHERE (result.service_id LIKE '%' + 6 || '%') AND (result.pa...
                                      ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nkane/eNMS/eNMS/server.py", line 81, in decorated_function
    return function(*args, **kwargs)
  File "/home/nkane/eNMS/eNMS/server.py", line 325, in route
    return jsonify(getattr(app, endpoint)(*args, **kwargs))
  File "/home/nkane/eNMS/eNMS/controller/base.py", line 502, in filtering
    filtered_records = query.with_entities(table.id).count()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3669, in count
    return self.from_self(col).scalar()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3393, in scalar
    ret = self.one()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3360, in one
    ret = self.one_or_none()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3329, in one_or_none
    ret = list(self)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3405, in __iter__
    return self._execute_and_instances(context)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context
    self._handle_dbapi_exception(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _handle_dbapi_exception
    util.raise_(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "%"
LINE 4: WHERE (result.service_id LIKE '%' + 6 || '%') AND (result.pa...
                                      ^

[SQL: SELECT count(*) AS count_1
FROM (SELECT result.id AS result_id
FROM result
WHERE (result.service_id LIKE '%%' + %(service_id_1)s || '%%') AND (result.parent_runtime LIKE '%%' || %(parent_runtime_1)s || '%%' ESCAPE '/')) AS anon_1]
[parameters: {'service_id_1': 6, 'parent_runtime_1': '2021-04-12 14:57:25.150859'}]
(Background on this error at: http://sqlalche.me/e/9h9h)

2021-04-12 14:57:33,011 ERROR    Traceback (most recent call last):
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: "%"
LINE 4: WHERE (result.service_id LIKE '%' + 6 || '%') AND (result.pa...
                                      ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nkane/eNMS/eNMS/server.py", line 81, in decorated_function
    return function(*args, **kwargs)
  File "/home/nkane/eNMS/eNMS/server.py", line 325, in route
    return jsonify(getattr(app, endpoint)(*args, **kwargs))
  File "/home/nkane/eNMS/eNMS/controller/base.py", line 502, in filtering
    filtered_records = query.with_entities(table.id).count()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3669, in count
    return self.from_self(col).scalar()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3393, in scalar
    ret = self.one()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3360, in one
    ret = self.one_or_none()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3329, in one_or_none
    ret = list(self)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3405, in __iter__
    return self._execute_and_instances(context)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context
    self._handle_dbapi_exception(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _handle_dbapi_exception
    util.raise_(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "%"
LINE 4: WHERE (result.service_id LIKE '%' + 6 || '%') AND (result.pa...
                                      ^

[SQL: SELECT count(*) AS count_1
FROM (SELECT result.id AS result_id
FROM result
WHERE (result.service_id LIKE '%%' + %(service_id_1)s || '%%') AND (result.parent_runtime LIKE '%%' || %(parent_runtime_1)s || '%%' ESCAPE '/')) AS anon_1]
[parameters: {'service_id_1': 6, 'parent_runtime_1': '2021-04-12 14:57:25.150859'}]
(Background on this error at: http://sqlalche.me/e/9h9h)

**Comment by afourmy** [comment]
looks like a NAPALM bug... what does NAPALM return on a cisco 2921 in a python script, outside of eNMS ? maybe that particular type of device just isn't supported by napalm

**Comment by nkane2898** [comment]
Connect to the device using the python shell on the same server running eNMS does work.

Python 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
>>> driver = get_network_driver('ios')
>>>
>>> device = driver('X.X.X.X' ,'username','password')
>>> device.open()
>>> device.get_facts()
{'uptime': 22963080, 'vendor': 'Cisco', 'os_version': 'C2900 Software (C2900-UNIVERSALK9-M), Version 15.7(3)M6, RELEASE SOFTWARE (fc1)', 'serial_number': 'Removed', 'model': 'CISCO2921/K9', 'hostname': 'Removed', 'fqdn': 'Removed', 'interface_list': ['Embedded-Service-Engine0/0', 'GigabitEthernet0/0', 'GigabitEthernet0/1', 'GigabitEthernet0/2']}

**Comment by nkane2898** [comment]
I found clicking the result button on the Inventory > Devices page also generates a similar error.

[2021-04-13 16:44:57 -0400] [30596] [DEBUG] POST /filtering/result
2021-04-13 16:44:57,203 ERROR    Traceback (most recent call last):
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: "%"
LINE 4: WHERE (result.device_id LIKE '%' + 191 || '%')) AS anon_1
                                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nkane/eNMS/eNMS/server.py", line 81, in decorated_function
    return function(*args, **kwargs)
  File "/home/nkane/eNMS/eNMS/server.py", line 325, in route
    return jsonify(getattr(app, endpoint)(*args, **kwargs))
  File "/home/nkane/eNMS/eNMS/controller/base.py", line 502, in filtering
    filtered_records = query.with_entities(table.id).count()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3064, in count
    return self._from_self(col).enable_eagerloads(False).scalar()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2805, in scalar
    ret = self.one()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2782, in one
    return self._iter().one()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2820, in _iter
    result = self.session.execute(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "%"
LINE 4: WHERE (result.device_id LIKE '%' + 191 || '%')) AS anon_1
                                     ^

[SQL: SELECT count(*) AS count_1
FROM (SELECT result.id AS result_id
FROM result
WHERE (result.device_id LIKE '%%' + %(device_id_1)s || '%%')) AS anon_1]
[parameters: {'device_id_1': 191}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

172.26.120.76 - - [13/Apr/2021:16:44:57 -0400] "POST /filtering/result HTTP/1.1" 200 52 "http://172.26.10.250:5000/device_table" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"

**Comment by nkane2898** [comment]
I create a new postgresql database and clone the repo and still have the issue. Click the results button on a device.

[2021-04-27 11:26:51 -0400] [23673] [DEBUG] POST /filtering/result
2021-04-27 11:26:51,084 ERROR    Traceback (most recent call last):
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: "%"
LINE 4: WHERE (result.device_id LIKE '%' + 169 || '%')) AS anon_1
                                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nkane/eNMS/eNMS/server.py", line 81, in decorated_function
    return function(*args, **kwargs)
  File "/home/nkane/eNMS/eNMS/server.py", line 325, in route
    return jsonify(getattr(app, endpoint)(*args, **kwargs))
  File "/home/nkane/eNMS/eNMS/controller/base.py", line 502, in filtering
    filtered_records = query.with_entities(table.id).count()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3064, in count
    return self._from_self(col).enable_eagerloads(False).scalar()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2805, in scalar
    ret = self.one()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2782, in one
    return self._iter().one()
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2820, in _iter
    result = self.session.execute(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/nkane/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "%"
LINE 4: WHERE (result.device_id LIKE '%' + 169 || '%')) AS anon_1
                                     ^

[SQL: SELECT count(*) AS count_1
FROM (SELECT result.id AS result_id
FROM result
WHERE (result.device_id LIKE '%%' + %(device_id_1)s || '%%')) AS anon_1]
[parameters: {'device_id_1': 169}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

172.26.120.76 - - [27/Apr/2021:11:26:51 -0400] "POST /filtering/result HTTP/1.1" 200 52 "http://172.26.10.250:5000/device_table" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0"

**Comment by afourmy** [comment]
eNMS is not tested with pgsql, only sqlite and mysql

**Comment by afourmy** [comment]
just pushed a fix, results display should be working with postgres now.
Can you test and let me know ?
