### ISSUE TITLE
Invalid Git Repository Error

### ISSUE THREAD

**Issue by kannankri** [eNMS-automation/eNMS#356]
I am getting the following error when trying to select the Configuration history option.

If someone could shed some light on this would be great. 

[2021-08-18 19:35:14 +0000] [2802414] [DEBUG] POST /get_git_history/1
2021-08-18 19:35:14,645 ERROR    Traceback (most recent call last):
  File "/home/azureuser/eNMS/eNMS/eNMS/server.py", line 81, in decorated_function
    return function(*args, **kwargs)
  File "/home/azureuser/eNMS/eNMS/eNMS/server.py", line 325, in route
    return jsonify(getattr(app, endpoint)(*args, **kwargs))
  File "/home/azureuser/eNMS/eNMS/eNMS/controller/inventory.py", line 120, in get_git_history
    repo = Repo(self.path / "network_data")
  File "/home/azureuser/eNMS/lib64/python3.6/site-packages/git/repo/base.py", line 220, in __init__
    self.working_dir = self._working_tree_dir or self.common_dir  # type: Optional[PathLike]
  File "/home/azureuser/eNMS/lib64/python3.6/site-packages/git/repo/base.py", line 303, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError

**Comment by jsmith7735** [comment]
@kannankri, I'm still having several issues with git as well but did you update the settings.json file with the correct remote git repository?

**Comment by kannankri** [comment]
It's working now. Thanks for your help
